apiVersion: v1 
kind: Secret
metadata: 
  name: git-ssh-key
  namespace: eazytraining
  annotations: 
    tekton.dev/git-0: ${GITHUB_HOST_FQDN}
type: kubernetes.io/ssh-auth
data: 
  ssh-privatekey: ${BASE64_PRIVATE_SSH_KEY}
  known_hosts: ${BASE64_KNOWN_HOSTS}