apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: gitops-dev-pipeline
spec:
  params:
    - default: 'https://github.com/eazytraining/openshift-administrator-training.git'
      description: Source to the GIT
      name: git-url
      type: string
    - default: main
      description: revision to be used
      name: git-revision
      type: string
    - name: config-git-url
      type: string
      description: URL of the Git config repository
      default: 'git@github.com:eazytraining/openshift-administrator-training.git'
    - name: git-branch
      type: string
      description: Branch Git to be used
      default: main
    - name: config-dir
      type: string
      description: Configuration directory within the config-git-url with the files
      default: 'tp4-deployment-app/cicd/config/overlays/dev'
    - name: image-name
      type: string
      description: the name of the target image including registry
      default: image-registry.openshift-image-registry.svc:5000/eazytraining/dck_eazytraining-lab-http:1.0
    - name: git-user-name
      type: string
      default: ObieBent
      description: The Git username
    - name: git-user-email
      type: string
      default: 'obiebent@gmail.com'
      description: The Git user email
    - default: ''               # Please provide your password
      name: git-password
      type: string
      description: The Git password
  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.git-url)
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: revision
          value: $(params.git-revision)
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: build-and-push-image
      params:
        - name: CONTEXT
          value: "tp4-deployment-app/s2i/sample-app-httpd/docker"
        - name: IMAGE
          value: >-
            image-registry.openshift-image-registry.svc:5000/eazytraining/dck_eazytraining-lab-http:1.0
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: buildah 
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: extract-digest
      runAfter:
        - build-and-push-image
      taskRef:
        kind: Task
        name: extract-sample-httpd-digest
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: git-update-deployment
      params:
        - name: GIT_REPOSITORY
          value: $(params.config-git-url)
        - name: GIT_USER_NAME
          value: $(params.git-user-name)
        - name: GIT_USER_EMAIL
          value: $(params.git-user-email)
        - name: GIT_PASSWORD
          value: $(params.git-password)
        - name: CURRENT_IMAGE
          value: image-registry.openshift-image-registry.svc:5000/eazytraining/dck_eazytraining-lab-http:1.0
        - name: NEW_IMAGE
          value: $(params.image-name)
        - name: NEW_DIGEST
          value: $(tasks.extract-digest.results.DIGEST)
        - name: KUSTOMIZATION_PATH
          value: $(params.config-dir)
        
      runAfter:
        - extract-digest
      taskRef:
        kind: Task
        name: git-update-deployment
      workspaces:
        - name: kustomize
          workspace: git-update-workspace
        - name: git-auth-dir
          workspace: git-credentials 
  workspaces:
    - name: shared-workspace
      optional: false
    - name: git-credentials
      optional: false
    - name: git-update-workspace
      optional: false