apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- digest: sha256:042a1fa3aee5966b189d07564f1611d6e2b0d0b474e105df7c05c364b119e76b
  name: image-registry.openshift-image-registry.svc:5000/eazytraining/dck_eazytraining-lab-http:1.0
  newName: image-registry.openshift-image-registry.svc:5000/eazytraining/dck_eazytraining-lab-http:1.0

namePrefix: dev-
commonLabels:
  variant: development

generatorOptions:
  disableNameSuffixHash: true

patches:
- patch: |-
    - op: replace
      path: /spec/to/name
      value: dev-svc-eazytraining-httpd
  target:
    kind: Route
